name: workflow 1
on: [push]

jobs:
  j0:
    name: job 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pwd step
        run: pwd
      - name: ls step
        run: ls -la